---
version: '2'

networks:
  cida-auth-net:

services:
  auth-database:
    image: auth-database:1.2.5
    build: ./auth-database
    ports:
      - "5432:5432"
    networks:
      cida-auth-net:
        aliases:
          - auth-database
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    
  auth-manager-core:
    image: auth-manager-core:1.2.5
    build: ./auth-manager-core
    ports:
      - "8080:8080"
    networks:
      cida-auth-net:
        aliases:
          - auth-manager-core
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"