---
version: '2'

networks:
  cida-auth-net:

services:
  ldap-server:
    image: osixia/openldap
    container_name: openldap
    hostname: ldap-cida-auth.org
    ports:
      - "389:389"
    networks:
      cida-auth-net:
        aliases:
          - ldap-server
    volumes:
      - /etc/ldap
      - /var/lib/ldap
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"

  ldap-seed:
    image: osixia/openldap
    volumes:
      - ./auth-ldap/ldif_files:/ldif_files/
    links:
      - ldap-server
    networks:
      cida-auth-net:
        aliases:
          - ldap-server
    entrypoint: sh -c '/ldif_files/addAll.sh'
    depends_on: 
      - ldap-server

  auth-database:
    image: auth-database:1.2.5
    build: ./auth-database
    ports:
      - "5432:5432"
    networks:
      cida-auth-net:
        aliases:
          - auth-database
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    
  auth-manager-console:
    image: auth-manager-console:1.2.5
    build: ./auth-manager-console
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      cida-auth-net:
        aliases:
          - auth-manager-console
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    depends_on:
      - auth-manager-core
    
  auth-manager-core:
    image: auth-manager-core:1.2.5
    build: ./auth-manager-core
    ports:
      - "8082:8080"
      - "8083:8081"
    networks:
      cida-auth-net:
        aliases:
          - auth-manager-core
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    depends_on:
      - auth-database